general:
  stage: "pretrain"
  corpus_type: "multi-unseen" # (single, multi-seen, multi-unseen)
  source_path: "./data/jvs_22k-spk_aug"
  aux_path: "./data/jvs_22k-spk"
  preprocessed_path: "./preprocessed/jvs_22k-spk"
  output_path: "./output/pretrain"
  test_wav_path: null
  feature_type: "melspec"
  hifigan_path: "./hifigan/hifigan_melspec_universal"
  power_norm: True
  use_gst: False
  aug_noise_dir: /home/saeki/workspace/hdd1/TUT2017_22k/train
  mix_channel: False

preprocess:
  n_val: 5
  n_test: 5
  sampling_rate: 22050
  frame_length: 1024
  frame_shift: 256
  fft_length: 1024
  fmin: 0
  fmax: 8000
  n_mels: 80
  comp_factor: 1.0
  min_magnitude: 0.00001
  max_wav_value: 32768.0
  segment_length: 2

train:
  batchsize: 8
  epoch: 50
  alpha: 0.01
  augment: True
  multi_gpu_mode: False
  num_workers: 4
  learning_rate: 0.005
  channel_kernel_size: 3
  grad_clip_thresh: 1.0
  logger_step: 1000
  load_pretrained: False
  pretrained_path: null
  early_stopping: False
  multi_scale_loss:
    use_linear: False
    gamma: 1.0
  feature_loss:
    type: "mae"
  
dual:
  enable: False
  config_path: ./configs/dual.yaml
  use_noise_aug: False
  noise_dir: /home/saeki/workspace/hdd1/TUT2017_22k/train